export { default as StudentHomePage } from './StudentHomePage'
export { default as StudentSubjectChoicePage } from './StudentSubjectChoicePage'
export { default as StudentConnectionPage } from './StudentConnectionPage'
export { default as StudentRegisterPage } from './StudentRegisterPage'
export { default as StudentChoicesClosedPage } from './StudentChoicesClosedPage'
